name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**' ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]
    paths: [ 'frontend/**' ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install & Build (frontend)
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_GROUND_0A4B52C1E }}
          action: upload
          app_location: ./frontend
          output_location: dist
          skip_app_build: true   # <-- key: bypass Oryx build
