
name: Build and deploy Python app to Azure Web App – pigeon-pool-backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/main_pigeon-pool-backend.yml'
  workflow_dispatch:

concurrency:
  group: deploy-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      PYTHON_VERSION: '3.12'
      APP_DIR: backend
      ZIP_NAME: release.zip

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: ${{ env.APP_DIR }}/requirements.txt

      - name: Create venv
        working-directory: ${{ env.APP_DIR }}
        run: python -m venv venv

      - name: Install dependencies
        working-directory: ${{ env.APP_DIR }}
        run: |
          source venv/bin/activate
          pip install --upgrade pip wheel
          pip install -r requirements.txt

      # Optional: run unit tests here (working-directory: backend)

      # Optional: run DB migrations (Alembic) against your PROD DB
      # - make sure connection string is in GitHub Environments or App Settings, not hard-coded
      # - name: Alembic upgrade head
      #   working-directory: ${{ env.APP_DIR }}
      #   env:
      #     DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
      #   run: |
      #     source venv/bin/activate
      #     alembic upgrade head

      - name: Zip artifact for deployment (include dotfiles)
        working-directory: ${{ env.APP_DIR }}
        run: |
          zip -r ${{ env.ZIP_NAME }} . \
            -x "venv/**" ".venv/**" "__pycache__/**" "*.pyc" \
               ".git/**" ".github/**" ".pytest_cache/**" "tests/**" \
               ".env.local" ".env.*.local"
          echo "Working Directory: $(pwd)"
          ls -lh ${{ env.ZIP_NAME }}
          # sanity: make sure no .env.* accidentally slipped in
          unzip -l ${{ env.ZIP_NAME }} | grep -E '\.env($|\.|/)' || true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pigeon-pool-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9434C8B104FA42D698A263DF9534D244 }}
          package: ${{ env.APP_DIR }}/${{ env.ZIP_NAME }}